
#version: "3.8"
#services:
#  backend:
#    build:
#      context: ./backend
#    ports:
#      - "8000:8000"
#    volumes:
#      - ./backend:/app

#  frontend:
#    build:
#      context: ./frontend
#    ports:
#      - "3000:80"
#    volumes:
#      - ./frontend:/app


services:
  ai_diabetes_prediction:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped

    environment:
      - PYTHONUNBUFFERED=1